name: Auto-approve own PRs

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Allows manual runs

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.pull_request.user.login == github.repository_owner
    permissions:
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - name: Auto-approve PR
        run: gh pr review ${{ github.event.pull_request.number }} --approve
        env:
          GITHUB_TOKEN: ${{ github.token }}